name: Test Latest NCBI Taxonomy
on:
  push:
    branches:
      - master
  pull_request:
  schedule:
    - cron: '0 0 1 * *' # runs at 00:00 on the 1st of every month (UTC)

jobs:
  test-ncbi-python-bindings:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          override: true

      - name: Setup Python bindings
        uses: ./.github/actions/setup-python-bindings

      - name: Test Python bindings with latest NCBI taxonomy
        run: |
          . venv/bin/activate
          TAXONOMY_TEST_NCBI=true pytest test_python.py::test_latestncbi_load_latest_ncbi_taxonomy
